<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-QL7K25G" failures="1" tests="1" name="Default test" time="55.52" errors="0" timestamp="2023-03-02T10:03:27 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="54.181">
    <failure type="java.lang.AssertionError" message="Order is not success: Failed expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Order is not success: Failed expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at stedDefinations.OrderPagestepDefinations.verify_order_is_success(OrderPagestepDefinations.java:46)
at âœ½.Verify order is success(file:///C:/Batch5/Denmark/src/test/java/features/Order.feature:17)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
